@startuml loader

class TExtensionMapper

class TFileLoader<T>
class TBufferLoader<T>

class "TFileLoader<TXMLModelLoader>" as ATXMLModelLoader
class "TFileLoader<TJsonModelLoader>" as ATJsonModelLoader

class "TBufferLoader<TXMLModelLoader>" as ATXMLModelLoader
class "TBufferLoader<TJsonModelLoader>" as ATJsonModelLoader

TFileLoader --> TExtensionMapper
TFileLoader --> ATXMLModelLoader
TFileLoader --> ATJsonModelLoader

TBufferLoader --> ATXMLModelLoader
TBufferLoader --> ATJsonModelLoader

@enduml
