name: CMake Build Matrix

on:
  push:
  pull_request:
  release:
    branches:
      - master

env:
  CMAKE_VERSION: 3.16.3

jobs:
  build-ubuntu:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install g++ ninja-build
      - name: Configure
        run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-windows:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --config ${{ matrix.build_type }}
      - name: test
        run: cd build && ctest -C ${{ matrix.build_type }}
