name: CMake Build Matrix

on:
  push:
  pull_request:
  release:
    branches:
      - master

env:
  CMAKE_VERSION: 3.16.3

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install g++ ninja-build
      - name: Configure
        run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest -C Debug
