name: CMake Build Matrix

on:
  push:
  pull_request:
  release:
    branches:
      - master

env:
  CMAKE_VERSION: 3.16.3

jobs:
  build-ubuntu:
    name: ${{ matrix.os }} ${{ matrix.build_type }} ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        cxx: [g++, g++-10]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install ${{ matrix.cxx }} ninja-build lcov
      - name: Check Coverage
        run: |
          if [[ ${{ matrix.build_type }} == 'Debug' && ${{ matrix.cxx }} == 'g++' ]]; then
            echo "COVERAGE=ON" >> "$GITHUB_ENV"
          else
            echo "COVERAGE=OFF" >> "$GITHUB_ENV"
          fi
          echo "Running with coverage ${{ env.COVERAGE }}"
      - name: Configure
        env:
          CXX: ${{ matrix.cxx }}
        run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCOVERAGE=${{ env.COVERAGE }} ..
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-windows:
    name: ${{ matrix.os }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --config ${{ matrix.build_type }}
      - name: test
        run: cd build && ctest --output-on-failure -C ${{ matrix.build_type }}
